{% set name = "trata" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/LLNL/trata/archive/refs/tags/{{ version }}.tar.gz
  sha256: 2db82d8c5e7792f05d199d2e7104c1c8b9fdb4b006f6ce3412b67db1f75d6f80

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python
  entry_points:
    - trata = trata.trata:__init__

requirements:
  host:
    - python >=3.7
    - pip
    - poetry
  run:
    - python >=3.7
    - scikit-learn
    - numpy
    - scipy
    - matplotlib-base

test:
  imports:
    - trata
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/LLNL/trata
  summary: 'Sampling Methods Package'
  description: |
    trata offers a large number of general sampling strategies that can be used to explore parameter spaces or improve a model's predictive ability.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://trata.readthedocs.io/
  dev_url: https://github.com/trata/trata

extra:
  recipe-maintainers:
    - olson59
    - doutriaux1
