{% set name = "trata" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/LLNL/trata/archive/refs/tags/{{ version }}.tar.gz
  sha256: 7fe3d97cba4ed00a12f7ebe750f9e04d27fe1230b44edea10d37b7eabc79fd27

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python
  entry_points:
    - trata = trata.trata:__init__

requirements:
  host:
    - python >=3.7
    - pip
    - poetry
  run:
    - python >=3.7
    - scikit-learn
    - numpy
    - scipy
    - matplotlib-base

test:
  imports:
    - trata
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/LLNL/trata
  summary: 'Sampling Methods Package'
  description: |
    trata offers a large number of general sampling strategies that can be used to explore parameter spaces or improve a model's predictive ability.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://trata.readthedocs.io/
  dev_url: https://github.com/trata/trata

extra:
  recipe-maintainers:
    - olson59
    - doutriaux1
